# Generated by Django 4.2.7 on 2025-10-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, help_text='User city for location-based services', max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, help_text='User role (e.g., customer, provider, admin)', max_length=50, null=True, verbose_name='User Role'),
        ),
        migrations.AddField(
            model_name='user',
            name='vaccinated',
            field=models.BooleanField(default=False, help_text='COVID-19 vaccination status', verbose_name='Vaccinated Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
