# Generated by Django 4.2.7 on 2025-10-06 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_user_city_user_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_version', models.CharField(help_text='Version of the policy/terms that was consented to', max_length=50, verbose_name='Policy Version')),
                ('consent_at', models.DateTimeField(auto_now_add=True, help_text='When the user gave consent', verbose_name='Consent Timestamp')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which consent was given', null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client information when consent was given', null=True, verbose_name='User Agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Consent Log',
                'verbose_name_plural': 'Consent Logs',
                'ordering': ['-consent_at'],
                'unique_together': {('user', 'policy_version')},
            },
        ),
    ]
