# Generated by Django 4.2.7 on 2025-10-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='provider_id',
            field=models.CharField(blank=True, help_text='Unique 16-digit ID for service providers', max_length=16, null=True, unique=True, verbose_name='Provider ID'),
        ),
    ]
