# Generated by Django 4.2.7 on 2025-10-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_provider_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderIDWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.CharField(help_text='16-digit provider ID', max_length=16, unique=True, verbose_name='Provider ID')),
                ('is_used', models.BooleanField(default=False, help_text='Whether this ID has been used for registration', verbose_name='Is Used')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('used_at', models.DateTimeField(blank=True, help_text='When this ID was used for registration', null=True, verbose_name='Used At')),
            ],
            options={
                'verbose_name': 'Provider ID Whitelist',
                'verbose_name_plural': 'Provider ID Whitelist',
                'ordering': ['-created_at'],
            },
        ),
    ]
