# Generated by Django 4.2.7 on 2025-10-18 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('cleaning', 'Home Cleaning'), ('plumbing', 'Plumbing Repair'), ('electrical', 'Electrical Services'), ('painting', 'Painting Services'), ('gardening', 'Gardening & Lawn Care'), ('carpentry', 'Carpentry Services'), ('appliance_repair', 'Appliance Repair'), ('pest_control', 'Pest Control'), ('hvac', 'HVAC Services'), ('moving', 'Moving Services'), ('other', 'Other Services')], default='other', help_text='Type of service requested', max_length=50, verbose_name='Service Type')),
                ('address_enc', models.BinaryField(help_text='Encrypted user address for privacy protection', verbose_name='Encrypted Address')),
                ('phone_enc', models.BinaryField(help_text='Encrypted user phone number for privacy protection', verbose_name='Encrypted Phone')),
                ('city', models.CharField(help_text='City where service is needed', max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, help_text='State or province where service is needed', max_length=100, null=True, verbose_name='State/Province')),
                ('country', models.CharField(default='US', help_text='Country where service is needed', max_length=100, verbose_name='Country')),
                ('start_time', models.DateTimeField(help_text='When the service should start', verbose_name='Start Time')),
                ('duration_hours', models.PositiveIntegerField(default=1, help_text='Expected duration of the service in hours', verbose_name='Duration (hours)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Booking Status')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or special instructions', null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'start_time'], name='bookings_bo_user_id_7b21ce_idx'), models.Index(fields=['city'], name='bookings_bo_city_eb9664_idx'), models.Index(fields=['status'], name='bookings_bo_status_233e96_idx'), models.Index(fields=['start_time'], name='bookings_bo_start_t_3f3843_idx')],
            },
        ),
    ]
