# Generated by Django 4.2.7 on 2025-10-18 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='provider',
            field=models.ForeignKey(blank=True, help_text='The provider who accepted this booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Provider'),
        ),
    ]
