# Generated by Django 4.2.7 on 2025-10-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Customer budget for the service', max_digits=10, null=True, verbose_name='Budget'),
        ),
    ]
