# Generated by Django 4.2.7 on 2025-10-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service_type',
            field=models.CharField(choices=[('cleaning', 'Home Cleaning'), ('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('gardening', 'Gardening'), ('other', 'Other')], default='other', help_text='Type of service requested', max_length=50, verbose_name='Service Type'),
        ),
    ]
