# Generated by Django 4.2.7 on 2025-10-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmation_code',
            field=models.CharField(default='0000', help_text='4-digit code for provider to start the job', max_length=4, verbose_name='Confirmation Code'),
        ),
    ]
