# Generated by Django 4.2.7 on 2025-10-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_confirmation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='provider_quote',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Provider quoted price for the service', max_digits=10, null=True, verbose_name='Provider Quote'),
        ),
    ]
