# Generated by Django 4.2.7 on 2025-10-06 06:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(help_text='Name of the service (e.g., "House Cleaning", "Plumbing Repair")', max_length=200, verbose_name='Service Title')),
                ('description', models.TextField(blank=True, help_text='Detailed description of what the service includes', null=True, verbose_name='Service Description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per hour or per service', max_digits=10, verbose_name='Service Price')),
                ('category', models.CharField(help_text='Category (e.g., "Cleaning", "Maintenance", "Emergency")', max_length=100, verbose_name='Service Category')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this service is currently available', verbose_name='Is Active')),
                ('estimated_duration', models.PositiveIntegerField(blank=True, help_text='Estimated time to complete the service in hours', null=True, verbose_name='Estimated Duration (hours)')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['category', 'title'],
            },
        ),
    ]
