# Generated by Django 4.2.7 on 2025-10-18 09:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount in USD', max_digits=10, verbose_name='Amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='Payment Status')),
                ('qr_token', models.CharField(blank=True, help_text='Unique token for QR code payments', max_length=64, null=True, unique=True, verbose_name='QR Token')),
                ('stripe_session_id', models.CharField(blank=True, help_text='Stripe checkout session ID', max_length=255, null=True, verbose_name='Stripe Session ID')),
                ('stripe_payment_intent_id', models.CharField(blank=True, help_text='Stripe payment intent ID', max_length=255, null=True, verbose_name='Stripe Payment Intent ID')),
                ('payment_method', models.CharField(blank=True, help_text='Payment method used (card, wallet, etc.)', max_length=50, null=True, verbose_name='Payment Method')),
                ('currency', models.CharField(default='USD', help_text='Payment currency (ISO 4217)', max_length=3, verbose_name='Currency')),
                ('metadata', models.JSONField(blank=True, help_text='Additional payment information as JSON', null=True, verbose_name='Payment Metadata')),
                ('paid_at', models.DateTimeField(blank=True, help_text='When payment was completed', null=True, verbose_name='Paid At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(help_text='The booking this payment is for', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking', verbose_name='Booking')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'), models.Index(fields=['qr_token'], name='payments_pa_qr_toke_388682_idx'), models.Index(fields=['stripe_session_id'], name='payments_pa_stripe__ab8e62_idx'), models.Index(fields=['stripe_payment_intent_id'], name='payments_pa_stripe__6fe52c_idx'), models.Index(fields=['created_at'], name='payments_pa_created_b8a300_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('booking',), name='unique_booking_payment'),
        ),
    ]
